quarkus.datasource.db-kind=mysql
quarkus.datasource.username=tu_user
quarkus.datasource.password=secretPass#2025
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3306/db_statement

# Habilitar Hibernate ORM
quarkus.hibernate-orm.database.generation=update
